// 자동차 도안 메타데이터 (24종 및 7대 분류)
export const CARS_DATA = [
  {
    id: 'lamborghini',
    name: '람보르기니 SVJ',
    nameEn: 'Lamborghini Aventador SVJ',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '어려움 (정밀)',
    description: '공기역학적 에어로 다이내믹 바디와 거대한 리어 윙을 갖춘 V12 플래그십 슈퍼카',
    image: 'images/cars/sports/lamborghini.jpg',
    defaultColor: '#ff2d55',
    accentColor: '#ffe600'
  },
  {
    id: 'porsche',
    name: '포르쉐 911 GT3',
    nameEn: 'Porsche 911 GT3 RS',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '보통',
    description: '레이스 트랙을 위해 태어난 전설적인 리어 엔진 스포츠카',
    image: 'images/cars/sports/porsche.jpg',
    defaultColor: '#30d158',
    accentColor: '#0a84ff'
  },
  {
    id: 'mustang',
    name: '포드 머스탱 GT',
    nameEn: 'Ford Mustang GT',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '쉬움',
    description: '강렬한 V8 엔진 배기음과 근육질 라인의 아메리칸 머슬카',
    image: 'images/cars/sports/mustang.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ffffff'
  },
  {
    id: 'mercedes',
    name: '메르세데스-AMG',
    nameEn: 'Mercedes-AMG GT',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '보통',
    description: '우아한 곡선미와 폭발적인 성능을 결합한 럭셔리 그랜드 투어러',
    image: 'images/cars/sports/mercedes.jpg',
    defaultColor: '#silver',
    accentColor: '#5e5ce6'
  },
  {
    id: 'grandeur',
    name: '현대 그랜저 GN7',
    nameEn: 'Hyundai Grandeur GN7',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '심리스 호라이즌 램프와 우아한 실루엣을 지닌 대한민국 대표 7세대 플래그십 세단',
    image: 'images/cars/sedan/grandeur.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#5e5ce6'
  },
  {
    id: 'grandeur_ig',
    name: '현대 그랜저 IG',
    nameEn: 'Hyundai Grandeur IG',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '캐스캐이딩 그릴과 세련된 LED 헤드램프의 역동적인 6세대 프리미엄 세단',
    image: 'images/cars/sedan/grandeur_ig.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#ff3b30'
  },
  {
    id: 'grandeur_hg',
    name: '현대 그랜저 HG',
    nameEn: 'Hyundai Grandeur HG',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '웅장한 폭포수 세로 그릴과 유려한 곡선의 플루이딕 스컬프처 5세대 그랜저',
    image: 'images/cars/sedan/grandeur_hg.jpg',
    defaultColor: '#2c2c2e',
    accentColor: '#ffd60a'
  },
  {
    id: 'sonata_yf',
    name: '현대 YF 쏘나타',
    nameEn: 'Hyundai YF Sonata',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '과감하고 날렵한 4도어 쿠페형 실루엣과 크롬 사이드 캐릭터 라인의 대표 중형 세단',
    image: 'images/cars/sedan/sonata_yf.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ffffff'
  },
  {
    id: 'freezer_truck',
    name: '냉동 탑차',
    nameEn: '1-Ton Refrigerated Box Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '보통',
    description: '신선한 식품과 냉동 식자재를 안전하게 일정한 저온으로 배송하는 1톤 특수 냉동 탑차',
    image: 'images/cars/truck/freezer_truck.jpg',
    defaultColor: '#ffffff',
    accentColor: '#0a84ff'
  },
  {
    id: 'truck',
    name: '일반 1톤 트럭',
    nameEn: '1-Ton Cargo Flatbed Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '쉬움',
    description: '물류와 짐을 든든하게 실어 나르는 친숙한 1톤 포터 카고 화물 트럭',
    image: 'images/cars/truck/truck.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ffffff'
  },
  {
    id: 'police',
    name: '경찰차 순찰차',
    nameEn: 'Police Patrol Cruiser',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '쉬움',
    description: '도시의 평화를 지키는 경광등과 사이렌이 달린 경찰 순찰차',
    image: 'images/cars/special/police.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#0a84ff'
  },
  {
    id: 'ambulance',
    name: '119 구급차',
    nameEn: 'Emergency Ambulance',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '보통',
    description: '응급 환자를 신속하게 병원으로 이송하는 최신형 구급차',
    image: 'images/cars/special/ambulance.jpg',
    defaultColor: '#ffffff',
    accentColor: '#ff453a'
  },
  {
    id: 'fire_truck',
    name: '소방차 레스큐',
    nameEn: 'Rescue Fire Engine',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '보통',
    description: '화재 진압 장비와 고성능 방수포를 탑재한 소방차',
    image: 'images/cars/special/fire_truck.jpg',
    defaultColor: '#ff3b30',
    accentColor: '#ffd60a'
  },
  {
    id: 'school_bus',
    name: '스쿨버스',
    nameEn: 'American School Bus',
    category: 'bus',
    categoryName: '승합차/버스',
    difficulty: '쉬움',
    description: '학생들을 안전하게 학교로 데려다주는 클래식 노란색 통학 버스',
    image: 'images/cars/bus/school_bus.jpg',
    defaultColor: '#ffcc00',
    accentColor: '#000000'
  },
  {
    id: 'monster_truck',
    name: '몬스터 트럭',
    nameEn: 'Monster Big-Foot Truck',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '거대한 메가 타이어와 하이 리프트 서스펜션의 괴물 트럭',
    image: 'images/cars/suv_mpv/monster_truck.jpg',
    defaultColor: '#bf5af2',
    accentColor: '#30d158'
  },
  {
    id: 'semi_truck',
    name: '세미 대형 트럭',
    nameEn: 'Heavy Duty Semi-Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '보통',
    description: '대륙을 횡단하며 물류를 운송하는 웅장한 크롬 그릴의 세미 트럭',
    image: 'images/cars/truck/semi_truck.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ff9f0a'
  },
  {
    id: 'jeep',
    name: '오프로드 지프',
    nameEn: 'Jeep Wrangler 4x4',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '바위산과 진흙길도 거침없이 질주하는 사륜구동 어드벤처 SUV',
    image: 'images/cars/suv_mpv/jeep.jpg',
    defaultColor: '#32d74b',
    accentColor: '#ff9f0a'
  },
  {
    id: 'excavator',
    name: '중장비 굴착기',
    nameEn: 'Hydraulic Excavator',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '어려움 (정밀)',
    description: '강력한 유압 붐대와 버킷으로 땅을 파고 건축을 돕는 파워 굴착기',
    image: 'images/cars/special/excavator.jpg',
    defaultColor: '#ff9f0a',
    accentColor: '#1c1c1e'
  },
  {
    id: 'tractor',
    name: '농업용 트랙터',
    nameEn: 'Heavy Farm Tractor',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '보통',
    description: '거대한 후륜 타이어로 밭을 일구는 현대적인 농업용 트랙터',
    image: 'images/cars/special/tractor.jpg',
    defaultColor: '#34c759',
    accentColor: '#ffd60a'
  },
  {
    id: 'f1_car',
    name: 'F1 포뮬러 레이스카',
    nameEn: 'Formula 1 Grand Prix Car',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '어려움 (정밀)',
    description: '서킷을 초고속으로 질주하는 최첨단 공기역학 에어로 바디의 F1 머신',
    image: 'images/cars/sports/f1_car.jpg',
    defaultColor: '#ff2d55',
    accentColor: '#00f0ff'
  },
  {
    id: 'cybertruck',
    name: '테슬라 사이버트럭',
    nameEn: 'Tesla Cybertruck EV',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '쉬움',
    description: '단단한 스테인리스 스틸 외골격과 미래지향적 다각형 앵글의 전기 픽업트럭',
    image: 'images/cars/suv_mpv/cybertruck.jpg',
    defaultColor: '#a1a8b8',
    accentColor: '#00f0ff'
  },
  {
    id: 'beetle',
    name: '폭스바겐 클래식 비틀',
    nameEn: 'Classic VW Beetle Bug',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '쉬움',
    description: '동글동글한 헤드램프와 둥근 휀더가 매력적인 시대를 초월한 클래식 딱정벌레차',
    image: 'images/cars/sedan/beetle.jpg',
    defaultColor: '#ffd60a',
    accentColor: '#ff3b30'
  },
  {
    id: 'minicooper',
    name: '미니 쿠퍼',
    nameEn: 'Mini Cooper S',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '보닛 스트라이프와 유니언 잭 감성의 스타일리시 어반 프리미엄 해치백',
    image: 'images/cars/sedan/minicooper.jpg',
    defaultColor: '#30d158',
    accentColor: '#ffffff'
  },
  {
    id: 'mixer',
    name: '레미콘 믹서트럭',
    nameEn: 'Concrete Cement Mixer Truck',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '어려움 (정밀)',
    description: '회전하는 드럼통으로 굳지 않게 콘크리트를 운반하는 든든한 건설 차량',
    image: 'images/cars/special/mixer.jpg',
    defaultColor: '#ff9f0a',
    accentColor: '#0a84ff'
  }
];

export const CATEGORIES = [
  { id: 'all', name: '전체 보기', image: 'images/categories/cat_all.svg' },
  { id: 'sedan', name: '승용차', image: 'images/categories/cat_sedan.svg' },
  { id: 'suv_mpv', name: 'SUV/CUV/MPV', image: 'images/categories/cat_suv.svg' },
  { id: 'sports', name: '스포츠카/고성능', image: 'images/categories/cat_sports.svg' },
  { id: 'truck', name: '화물차', image: 'images/categories/cat_truck.svg' },
  { id: 'bus', name: '승합차/버스', image: 'images/categories/cat_bus.svg' },
  { id: 'special', name: '특수목적차', image: 'images/categories/cat_special.svg' },
  { id: 'micro', name: '이륜/소형 이동수단', image: 'images/categories/cat_micro.svg' }
];
