// 자동차 도안 메타데이터 (24종 및 7대 분류)
export const CARS_DATA = [
  {
    id: 'lamborghini',
    name: '람보르기니 SVJ',
    nameEn: 'Lamborghini Aventador SVJ',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '어려움 (정밀)',
    description: '공기역학적 에어로 다이내믹 바디와 거대한 리어 윙을 갖춘 V12 플래그십 슈퍼카',
    image: 'images/cars/sports/lamborghini.jpg',
    defaultColor: '#ff2d55',
    accentColor: '#ffe600'
  },
  {
    id: 'porsche',
    name: '포르쉐 911 GT3',
    nameEn: 'Porsche 911 GT3 RS',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '보통',
    description: '레이스 트랙을 위해 태어난 전설적인 리어 엔진 스포츠카',
    image: 'images/cars/sports/porsche.jpg',
    defaultColor: '#30d158',
    accentColor: '#0a84ff'
  },
  {
    id: 'mustang',
    name: '포드 머스탱 GT',
    nameEn: 'Ford Mustang GT',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '쉬움',
    description: '강렬한 V8 엔진 배기음과 근육질 라인의 아메리칸 머슬카',
    image: 'images/cars/sports/mustang.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ffffff'
  },
  {
    id: 'mercedes',
    name: '메르세데스-AMG',
    nameEn: 'Mercedes-AMG GT',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '보통',
    description: '우아한 곡선미와 폭발적인 성능을 결합한 럭셔리 그랜드 투어러',
    image: 'images/cars/sports/mercedes.jpg',
    defaultColor: '#c0c0c0',
    accentColor: '#5e5ce6'
  },
  {
    id: 'grandeur',
    name: '현대 그랜저 GN7',
    nameEn: 'Hyundai Grandeur GN7',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '심리스 호라이즌 램프와 우아한 실루엣을 지닌 대한민국 대표 7세대 플래그십 세단',
    image: 'images/cars/sedan/grandeur.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#5e5ce6'
  },
  {
    id: 'grandeur_ig',
    name: '현대 그랜저 IG',
    nameEn: 'Hyundai Grandeur IG',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '캐스캐이딩 그릴과 세련된 LED 헤드램프의 역동적인 6세대 프리미엄 세단',
    image: 'images/cars/sedan/grandeur_ig.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#ff3b30'
  },
  {
    id: 'grandeur_hg',
    name: '현대 그랜저 HG',
    nameEn: 'Hyundai Grandeur HG',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '웅장한 폭포수 세로 그릴과 유려한 곡선의 플루이딕 스컬프처 5세대 그랜저',
    image: 'images/cars/sedan/grandeur_hg.jpg',
    defaultColor: '#2c2c2e',
    accentColor: '#ffd60a'
  },
  {
    id: 'sonata_yf',
    name: '현대 YF 쏘나타',
    nameEn: 'Hyundai YF Sonata',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '과감하고 날렵한 4도어 쿠페형 실루엣과 크롬 사이드 캐릭터 라인의 대표 중형 세단',
    image: 'images/cars/sedan/sonata_yf.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ffffff'
  },
  {
    id: 'freezer_truck',
    name: '냉동 탑차',
    nameEn: '1-Ton Refrigerated Box Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '보통',
    description: '신선한 식품과 냉동 식자재를 안전하게 일정한 저온으로 배송하는 1톤 특수 냉동 탑차',
    image: 'images/cars/truck/freezer_truck.jpg',
    defaultColor: '#ffffff',
    accentColor: '#0a84ff'
  },
  {
    id: 'truck',
    name: '일반 1톤 트럭',
    nameEn: '1-Ton Cargo Flatbed Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '쉬움',
    description: '물류와 짐을 든든하게 실어 나르는 친숙한 1톤 포터 카고 화물 트럭',
    image: 'images/cars/truck/truck.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ffffff'
  },
  {
    id: 'police',
    name: '경찰차 순찰차',
    nameEn: 'Police Patrol Cruiser',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '쉬움',
    description: '도시의 평화를 지키는 경광등과 사이렌이 달린 경찰 순찰차',
    image: 'images/cars/special/police.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#0a84ff'
  },
  {
    id: 'ambulance',
    name: '119 구급차',
    nameEn: 'Emergency Ambulance',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '보통',
    description: '응급 환자를 신속하게 병원으로 이송하는 최신형 구급차',
    image: 'images/cars/special/ambulance.jpg',
    defaultColor: '#ffffff',
    accentColor: '#ff453a'
  },
  {
    id: 'fire_truck',
    name: '소방차 레스큐',
    nameEn: 'Rescue Fire Engine',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '보통',
    description: '화재 진압 장비와 고성능 방수포를 탑재한 소방차',
    image: 'images/cars/special/fire_truck.jpg',
    defaultColor: '#ff3b30',
    accentColor: '#ffd60a'
  },
  {
    id: 'school_bus',
    name: '스쿨버스',
    nameEn: 'American School Bus',
    category: 'bus',
    categoryName: '승합차/버스',
    difficulty: '쉬움',
    description: '학생들을 안전하게 학교로 데려다주는 클래식 노란색 통학 버스',
    image: 'images/cars/bus/school_bus.jpg',
    defaultColor: '#ffcc00',
    accentColor: '#000000'
  },
  {
    id: 'monster_truck',
    name: '몬스터 트럭',
    nameEn: 'Monster Big-Foot Truck',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '거대한 메가 타이어와 하이 리프트 서스펜션의 괴물 트럭',
    image: 'images/cars/suv_mpv/monster_truck.jpg',
    defaultColor: '#bf5af2',
    accentColor: '#30d158'
  },
  {
    id: 'semi_truck',
    name: '세미 대형 트럭',
    nameEn: 'Heavy Duty Semi-Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '보통',
    description: '대륙을 횡단하며 물류를 운송하는 웅장한 크롬 그릴의 세미 트럭',
    image: 'images/cars/truck/semi_truck.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ff9f0a'
  },
  {
    id: 'jeep',
    name: '오프로드 지프',
    nameEn: 'Jeep Wrangler 4x4',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '바위산과 진흙길도 거침없이 질주하는 사륜구동 어드벤처 SUV',
    image: 'images/cars/suv_mpv/jeep.jpg',
    defaultColor: '#32d74b',
    accentColor: '#ff9f0a'
  },
  {
    id: 'excavator',
    name: '중장비 굴착기',
    nameEn: 'Hydraulic Excavator',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '어려움 (정밀)',
    description: '강력한 유압 붐대와 버킷으로 땅을 파고 건축을 돕는 파워 굴착기',
    image: 'images/cars/special/excavator.jpg',
    defaultColor: '#ff9f0a',
    accentColor: '#1c1c1e'
  },
  {
    id: 'tractor',
    name: '농업용 트랙터',
    nameEn: 'Heavy Farm Tractor',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '보통',
    description: '거대한 후륜 타이어로 밭을 일구는 현대적인 농업용 트랙터',
    image: 'images/cars/special/tractor.jpg',
    defaultColor: '#34c759',
    accentColor: '#ffd60a'
  },
  {
    id: 'f1_car',
    name: 'F1 포뮬러 레이스카',
    nameEn: 'Formula 1 Grand Prix Car',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '어려움 (정밀)',
    description: '서킷을 초고속으로 질주하는 최첨단 공기역학 에어로 바디의 F1 머신',
    image: 'images/cars/sports/f1_car.jpg',
    defaultColor: '#ff2d55',
    accentColor: '#00f0ff'
  },
  {
    id: 'cybertruck',
    name: '테슬라 사이버트럭',
    nameEn: 'Tesla Cybertruck EV',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '쉬움',
    description: '단단한 스테인리스 스틸 외골격과 미래지향적 다각형 앵글의 전기 픽업트럭',
    image: 'images/cars/suv_mpv/cybertruck.jpg',
    defaultColor: '#a1a8b8',
    accentColor: '#00f0ff'
  },
  {
    id: 'beetle',
    name: '폭스바겐 클래식 비틀',
    nameEn: 'Classic VW Beetle Bug',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '쉬움',
    description: '동글동글한 헤드램프와 둥근 휀더가 매력적인 시대를 초월한 클래식 딱정벌레차',
    image: 'images/cars/sedan/beetle.jpg',
    defaultColor: '#ffd60a',
    accentColor: '#ff3b30'
  },
  {
    id: 'minicooper',
    name: '미니 쿠퍼',
    nameEn: 'Mini Cooper S',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '보닛 스트라이프와 유니언 잭 감성의 스타일리시 어반 프리미엄 해치백',
    image: 'images/cars/sedan/minicooper.jpg',
    defaultColor: '#30d158',
    accentColor: '#ffffff'
  },
  {
    id: 'mixer',
    name: '레미콘 믹서트럭',
    nameEn: 'Concrete Cement Mixer Truck',
    category: 'special',
    categoryName: '특수목적차',
    difficulty: '어려움 (정밀)',
    description: '회전하는 드럼통으로 굳지 않게 콘크리트를 운반하는 든든한 건설 차량',
    image: 'images/cars/special/mixer.jpg',
    defaultColor: '#ff9f0a',
    accentColor: '#0a84ff'
  },
  {
    id: 'avante_cn7',
    name: '현대 아반떼 CN7',
    nameEn: 'Hyundai Elantra Avante CN7',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '파라메트릭 다이내믹스 기하학적 캐릭터 라인과 날렵한 LED 램프의 준중형 세단',
    image: 'images/cars/sedan/avante_cn7.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ffffff'
  },
  {
    id: 'genesis_g80',
    name: '제네시스 G80',
    nameEn: 'Genesis G80 Luxury Sedan',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '지-매트릭스 크레스트 그릴과 쿼드램프, 유려한 파라볼릭 라인의 프리미엄 세단',
    image: 'images/cars/sedan/genesis_g80.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#5e5ce6'
  },
  {
    id: 'bmw_5series',
    name: 'BMW 5시리즈',
    nameEn: 'BMW 5 Series Sedan',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '보통',
    description: '아이코닉 키드니 그릴과 트윈 헤드라이트, 스포티한 주행 감성의 비즈니스 세단',
    image: 'images/cars/sedan/bmw_5series.jpg',
    defaultColor: '#004080',
    accentColor: '#00f0ff'
  },
  {
    id: 'tesla_model3',
    name: '테슬라 모델 3',
    nameEn: 'Tesla Model 3 EV',
    category: 'sedan',
    categoryName: '승용차',
    difficulty: '쉬움',
    description: '그릴리스 에어로 바디와 글래스 루프가 돋보이는 미래지향적 순수 전기 세단',
    image: 'images/cars/sedan/tesla_model3.jpg',
    defaultColor: '#ff3b30',
    accentColor: '#ffffff'
  },
  {
    id: 'carnival',
    name: '기아 카니발',
    nameEn: 'Kia Carnival Grand MPV',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '스타맵 시그니처 라이팅과 웅장한 크롬 그릴, 슬라이딩 도어의 패밀리 미니밴',
    image: 'images/cars/suv_mpv/carnival.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#c0c0c0'
  },
  {
    id: 'gv80',
    name: '제네시스 GV80',
    nameEn: 'Genesis GV80 Luxury SUV',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '두 줄 쿼드램프와 웅장한 볼륨감, 역동적인 우아함을 지닌 플래그십 럭셔리 SUV',
    image: 'images/cars/suv_mpv/gv80.jpg',
    defaultColor: '#2c3e50',
    accentColor: '#ffd60a'
  },
  {
    id: 'g_wagon',
    name: '메르세데스 G-클래스',
    nameEn: 'Mercedes-Benz G-Wagon 4x4',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '아이코닉한 각진 차체와 원형 LED 램프, 스페어 타이어를 갖춘 전설의 정통 오프로더',
    image: 'images/cars/suv_mpv/g_wagon.jpg',
    defaultColor: '#1c1c1e',
    accentColor: '#ff3b30'
  },
  {
    id: 'palisade',
    name: '현대 팰리세이드',
    nameEn: 'Hyundai Palisade Full-Size SUV',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '수직형 LED 주간주행등과 웅장한 캐스케이딩 그릴을 자랑하는 대형 플래그십 SUV',
    image: 'images/cars/suv_mpv/palisade.jpg',
    defaultColor: '#2c2c2e',
    accentColor: '#30d158'
  },
  {
    id: 'range_rover',
    name: '랜드로버 레인지로버',
    nameEn: 'Range Rover Luxury Flagship',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '플로팅 루프와 플러시 도어 핸들, 매끄러운 바디 실루엣의 황제급 럭셔리 SUV',
    image: 'images/cars/suv_mpv/range_rover.jpg',
    defaultColor: '#003322',
    accentColor: '#ff9f0a'
  },
  {
    id: 'santafe_mx5',
    name: '현대 싼타페 MX5',
    nameEn: 'Hyundai Santa Fe MX5',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '독창적인 H 라이트와 박시한 아웃도어 감성의 5세대 패밀리 SUV',
    image: 'images/cars/suv_mpv/santafe_mx5.jpg',
    defaultColor: '#5c6b73',
    accentColor: '#ff9f0a'
  },
  {
    id: 'kia_ev9',
    name: '기아 EV9',
    nameEn: 'Kia EV9 Electric SUV',
    category: 'suv_mpv',
    categoryName: 'SUV/CUV/MPV',
    difficulty: '보통',
    description: '디지털 타이거 페이스와 스타맵 램프, 미래지향적 다각형 휠의 플래그십 전기 SUV',
    image: 'images/cars/suv_mpv/kia_ev9.jpg',
    defaultColor: '#00f0ff',
    accentColor: '#1c1c1e'
  },
  {
    id: 'bugatti_chiron',
    name: '부가티 시론',
    nameEn: 'Bugatti Chiron Hypercar',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '어려움 (정밀)',
    description: '시그니처 C라인 에어로 커브와 말굽형 그릴, 최고출력 1500마력의 궁극 하이퍼카',
    image: 'images/cars/sports/bugatti_chiron.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#1c1c1e'
  },
  {
    id: 'ferrari_sf90',
    name: '페라리 SF90 스트라달레',
    nameEn: 'Ferrari SF90 Stradale',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '어려움 (정밀)',
    description: 'F1 기술을 접목한 날렵한 프론트 스플리터와 C자형 매트릭스 LED의 플러그인 하이브리드 슈퍼카',
    image: 'images/cars/sports/ferrari_sf90.jpg',
    defaultColor: '#ff2d55',
    accentColor: '#ffe600'
  },
  {
    id: 'mclaren_720s',
    name: '맥라렌 720S',
    nameEn: 'McLaren 720S Supercar',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '어려움 (정밀)',
    description: '아이 소켓 헤드램프와 다이히드럴 버터플라이 도어, 물방울 캐빈의 영국 슈퍼카',
    image: 'images/cars/sports/mclaren_720s.jpg',
    defaultColor: '#ff9f0a',
    accentColor: '#1c1c1e'
  },
  {
    id: 'audi_r8',
    name: '아우디 R8 V10',
    nameEn: 'Audi R8 V10 Plus',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '보통',
    description: '허니컴 싱글프레임 그릴과 도어 뒤 카본 사이드블레이드가 빛나는 V10 미드십 슈퍼카',
    image: 'images/cars/sports/audi_r8.jpg',
    defaultColor: '#ffd60a',
    accentColor: '#1c1c1e'
  },
  {
    id: 'chevrolet_corvette',
    name: '쉐보레 콜벳 Z06',
    nameEn: 'Chevrolet Corvette Z06 C8',
    category: 'sports',
    categoryName: '스포츠카/고성능',
    difficulty: '보통',
    description: '미드엔진 아키텍처와 와이드 리어 윙, 날렵한 위시본 에어 인테이크의 아메리칸 슈퍼카',
    image: 'images/cars/sports/chevrolet_corvette.jpg',
    defaultColor: '#ff453a',
    accentColor: '#ffffff'
  },
  {
    id: 'dump_truck',
    name: '25톤 덤프트럭',
    nameEn: '25-Ton Heavy Duty Dump Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '보통',
    description: '흙과 모래를 실어 나르고 유압 실린더로 적재함을 들어 올리는 25톤 대형 건설 덤프트럭',
    image: 'images/cars/truck/dump_truck.jpg',
    defaultColor: '#ff9f0a',
    accentColor: '#1c1c1e'
  },
  {
    id: 'tow_truck',
    name: '렉카 구난 견인차',
    nameEn: 'Emergency Wrecker Tow Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '어려움 (정밀)',
    description: '고장 차량을 안전하게 견인하는 유압 크레인 붐대와 휠 리프트 장치를 갖춘 구난차',
    image: 'images/cars/truck/tow_truck.jpg',
    defaultColor: '#ffffff',
    accentColor: '#ff3b30'
  },
  {
    id: 'tanker_truck',
    name: '대형 탱크로리 트럭',
    nameEn: 'Heavy Liquid Fuel Tanker Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '보통',
    description: '원통형 대용량 저장 탱크와 배관 밸브를 탑재해 유류 및 액체를 안전하게 운송하는 탱크로리',
    image: 'images/cars/truck/tanker_truck.jpg',
    defaultColor: '#c0c0c0',
    accentColor: '#0a84ff'
  },
  {
    id: 'garbage_truck',
    name: '압축 청소차',
    nameEn: 'City Waste Compactor Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '보통',
    description: '도시의 거리를 깨끗하게 정비하는 강력한 유압 회전 압축식 수거 청소 트럭',
    image: 'images/cars/truck/garbage_truck.jpg',
    defaultColor: '#30d158',
    accentColor: '#ffffff'
  },
  {
    id: 'car_carrier',
    name: '카캐리어 탁송 트럭',
    nameEn: 'Auto Transporter Car Carrier Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '어려움 (정밀)',
    description: '여러 대의 승용차를 위아래 2단 데크에 가득 싣고 도로를 달리는 거대한 차량 탁송 트럭',
    image: 'images/cars/truck/car_carrier.jpg',
    defaultColor: '#0a84ff',
    accentColor: '#ff9f0a'
  },
  {
    id: 'electric_delivery_van',
    name: '친환경 전기 택배 밴',
    nameEn: 'Electric Parcel Delivery Cargo Van',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '쉬움',
    description: '슬라이딩 도어와 높은 천장으로 빠르고 편리하게 택배를 배송하는 도심형 전기 카고 밴',
    image: 'images/cars/truck/electric_delivery_van.jpg',
    defaultColor: '#ffd60a',
    accentColor: '#1c1c1e'
  },
  {
    id: 'military_truck',
    name: '군용 6x6 전술 트럭',
    nameEn: 'Heavy 6x6 Tactical Military Truck',
    category: 'truck',
    categoryName: '화물차',
    difficulty: '보통',
    description: '거친 험지와 도하 구역도 거침없이 돌파하는 6륜 구동 스노클 및 범퍼 가드 전술 트럭',
    image: 'images/cars/truck/military_truck.jpg',
    defaultColor: '#4a5d4e',
    accentColor: '#1c1c1e'
  }
];

export const CATEGORIES = [
  { id: 'all', name: '전체 보기', image: 'images/categories/cat_all.svg' },
  { id: 'sedan', name: '승용차', image: 'images/categories/cat_sedan.svg' },
  { id: 'suv_mpv', name: 'SUV/CUV/MPV', image: 'images/categories/cat_suv.svg' },
  { id: 'sports', name: '스포츠카/고성능', image: 'images/categories/cat_sports.svg' },
  { id: 'truck', name: '화물차', image: 'images/categories/cat_truck.svg' },
  { id: 'bus', name: '승합차/버스', image: 'images/categories/cat_bus.svg' },
  { id: 'special', name: '특수목적차', image: 'images/categories/cat_special.svg' },
  { id: 'micro', name: '이륜/소형 이동수단', image: 'images/categories/cat_micro.svg' }
];
